"""World Cup 2026 discovery constants (no DB/pipeline imports)."""

WC_EGT_SEARCH_TERMS = [
    "Mexico",
    "South Africa",
    "Korea",
    "Czech",
    "Canada",
    "Bosnia",
    "USA",
    "Paraguay",
    "Qatar",
    "Switzerland",
    "Brazil",
    "Morocco",
    "Haiti",
    "Scotland",
    "Australia",
    "Turkey",
    "Germany",
    "Netherlands",
    "Japan",
    "France",
    "Spain",
    "England",
    "Argentina",
    "Portugal",
    "Belgium",
    "Croatia",
    "Uruguay",
    "Colombia",
    "Ecuador",
    "Chile",
    "Italy",
    "Poland",
    "Serbia",
    "Denmark",
    "Sweden",
    "Norway",
    "Austria",
    "Ukraine",
    "Wales",
    "Iran",
    "Saudi",
    "Senegal",
    "Ghana",
    "Cameroon",
    "Tunisia",
    "Egypt",
    "Costa Rica",
    "Panama",
    "Jamaica",
    "Curacao",
]
